---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horizon-web
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: horizon
        component: web
        layer: application
      name: horizon-web
    spec:
      containers:
        - name: horizon-web
          env:
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: horizon-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/horizon:production
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 8080
            - containerPort: 8443
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 500Mi
          readinessProbe:
            httpGet:
              port: 3000
              path: /robots.txt
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: horizon-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: horizon-web
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: horizon
    component: web
    layer: application
  name: horizon-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: 8443
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: horizon
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/12
    - 172.64.0.0/13
    - 131.0.72.0/22
# ---
# apiVersion: batch/v2alpha1
# kind: CronJob
# metadata:
#   name: horizon-refresh-cron
# spec:
#   schedule: "*/10 * * * *"
#   concurrencyPolicy: Forbid
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: horizon-refresh-cron
#             image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/horizon:production
#             args: ["bundle", "exec", "rake", "cron:refresh_comparisons"]
#             imagePullPolicy: Always
#             envFrom:
#             - configMapRef:
#                 name: horizon-environment
#           restartPolicy: Never
#           affinity:
#             nodeAffinity:
#               preferredDuringSchedulingIgnoredDuringExecution:
#               - weight: 1
#                 preference:
#                   matchExpressions:
#                   - key: tier
#                     operator: In
#                     values:
#                     - background
