---
version: "3.8"
services:
  horizon:
    build:
      target: builder
{% include 'templates/docker-compose-build.j2' %}
    command: ./hokusai/ci.sh
    environment:
{% include 'templates/docker-compose-environment.j2' %}
      - DATABASE_URL=postgresql://postgres:@horizon-postgres/horizon_test
      - RAILS_ENV=test
      - REDIS_URL=redis://horizon-redis
    depends_on:
      - horizon-postgres
      - horizon-redis
  horizon-postgres:
    image: postgres:13.20-alpine
    environment:
      - POSTGRES_DB=horizon_test
      - POSTGRES_HOST_AUTH_METHOD=trust
  horizon-redis:
    image: redis:3.2-alpine
